preprocessing:
  max_train_lines: 20000
  max_test_lines: 5000
  max_valid_lines: 100
  max_sentence_length: 30
  data_dir: "/scratch1/mcipriano/SCLIP/"
  out_dir: "/home/mcipriano/projects/SCLIP/europarl"

spanish_preprocessing:
  max_train_lines: 1000
  max_test_lines: 100
  max_valid_lines: 100
  max_sentence_length: 30
  data_dir: "/scratch1/mcipriano/SCLIP/"
  out_dir: "/home/mcipriano/projects/SCLIP/europarl_es"

coco:
  max_train_lines: 1000
  max_test_lines: 100
  max_valid_lines: 100
  max_sentence_length: 30
  caption_dir: "/scratch1/mcipriano/SCLIP/annotations"
  image_dir:  "/scratch1/mcipriano/SCLIP/val2017"
  out_dir: "/home/mcipriano/projects/SCLIP/coco"

languages:
  english: en
  spanish: es
