# Preprocessing
europarl:
  max_train_lines: 1000
  max_test_lines: 100
  max_valid_lines: 100
  max_sentence_length: 70
  data_dir: "/home/users/acordova/project/SCLIP/europarl"
  out_dir: "/home/users/acordova/project/SCLIP/europarl"

spanish_europarl:
  max_train_lines: 1000
  max_test_lines: 100
  max_valid_lines: 100
  max_sentence_length: 30
  data_dir: "/home/users/acordova/project/SCLIP/europarl_es"
  out_dir: "/home/users/acordova/project/SCLIP/europarl_es"

coco:
  max_train_lines: 1000
  max_test_lines: 100
  max_valid_lines: 100
  max_sentence_length: 30
  pairs: 450
  caption_dir: "/home/users/acordova/project/SCLIP/coco/annotations"  
  image_dir:  "/home/users/acordova/project/SCLIP/coco/images/val2017"
  data_dir: "/home/users/acordova/project/SCLIP/coco"
  out_dir: "/home/users/acordova/project/SCLIP/coco"

esco:
  max_train_lines: 1000
  max_test_lines: 100
  max_valid_lines: 100
  max_sentence_length: 30
  data_dir: "/home/users/acordova/project/SCLIP/esco"
  out_dir: "/home/users/acordova/project/SCLIP/esco"
  
gcc:
  max_train_lines: 1000
  max_test_lines: 100
  max_valid_lines: 100
  max_sentence_length: 30
  data_dir: "/home/users/acordova/project/SCLIP/gcc"
  out_dir: "/home/users/acordova/project/SCLIP/gcc"

mix:
  size: 1000
  europarl_dir : "/home/users/acordova/project/SCLIP/europarl"
  coco_dir: "/home/users/acordova/project/SCLIP/coco"
  out_dir: "/home/users/acordova/project/SCLIP/mix"

models:
    model_dir: "/home/users/acordova/project/SCLIP/models"
languages:
  english: en
  spanish: es
  italian: it
  german: de
  french: fr
  
