europarl:
  max_train_lines: 1000
  max_test_lines: 100
  max_valid_lines: 100
  max_sentence_length: 70
  data_dir: "/home/users/acordova/SCLIP/europarl"
  out_dir: "/home/users/acordova/SCLIP/europarl"

spanish_europarl:
  max_train_lines: 1000
  max_test_lines: 100
  max_valid_lines: 100
  max_sentence_length: 30
  data_dir: "/home/users/acordova/SCLIP/europarl_es"
  out_dir: "/home/users/acordova/SCLIP/europarl_es"

coco:
  max_train_lines: 1000
  max_test_lines: 100
  max_valid_lines: 100
  max_sentence_length: 30
  caption_dir: "/home/users/acordova/SCLIP/coco/annotations"  
  image_dir:  "/home/users/acordova/SCLIP/coco/images/val2017"
  data_dir: "/home/users/acordova/SCLIP/coco"
  out_dir: "/home/users/acordova/SCLIP/coco"

test:
  size: 1000
  europarl_dir : "/home/users/acordova/SCLIP/europarl"
  coco_dir: "/home/users/acordova/SCLIP/coco"
  out_dir: "/home/users/acordova/SCLIP/"
  
languages:
  english: en
  spanish: es
  italian: it
