# Preprocessing
europarl:
  max_train_lines: 1000
  max_test_lines: 100
  max_valid_lines: 100
  max_sentence_length: 70
  data_dir: "/home/acordova/SCLIP/europarl"
  out_dir: "/home/acordova/SCLIP/europarl"

spanish_europarl:
  max_train_lines: 1000
  max_test_lines: 100
  max_valid_lines: 100
  max_sentence_length: 30
  data_dir: "/home/acordova/SCLIP/europarl_es"
  out_dir: "/home/acordova/SCLIP/europarl_es"

coco:
  max_train_lines: 1000
  max_test_lines: 100
  max_valid_lines: 100
  max_sentence_length: 30
  pairs: 450
  caption_dir: "/home/acordova/SCLIP/coco/annotations"  
  image_dir:  "/home/acordova/SCLIP/coco/images/val2017"
  data_dir: "/home/acordova/SCLIP/coco"
  out_dir: "/home/acordova/SCLIP/coco"
  
crossmodal:
  max_train_lines: 2880
  max_test_lines: 100
  max_valid_lines: 720
  max_sentence_length: 30
  pairs: 450
  caption_dir: "/home/acordova/SCLIP/crossmodal"
  image_dir:  "/home/acordova/SCLIP/crossmodal/images"
  data_dir: "/home/acordova/SCLIP/crossmodal"
  out_dir: "/home/acordova/SCLIP/crossmodal"

esco:
  max_train_lines: 1000
  max_test_lines: 100
  max_valid_lines: 100
  max_sentence_length: 30
  data_dir: "/home/acordova/SCLIP/esco"
  out_dir: "/home/acordova/SCLIP/esco"
  
gcc:
  max_train_lines: 1000
  max_test_lines: 100
  max_valid_lines: 100
  max_sentence_length: 30
  data_dir: "/home/acordova/SCLIP/gcc"
  out_dir: "/home/acordova/SCLIP/gcc"
  
gco:
  max_train_lines: 1000
  max_test_lines: 100
  max_valid_lines: 100
  max_sentence_length: 30
  data_dir: "/home/acordova/SCLIP/gco"
  out_dir: "/home/acordova/SCLIP/gco"

mix:
  size: 1000
  europarl_dir : "/home/acordova/SCLIP/europarl"
  coco_dir: "/home/acordova/SCLIP/coco"
  out_dir: "/home/acordova/SCLIP/mix"

models:
    model_dir: "models"
    
languages:
  english: en
  spanish: es
  italian: it
  german: de
  french: fr
  
otherlangugages:
    polish: pl